### ISSUE TITLE
Error when running the script

### ISSUE THREAD

**Issue by adamh3105** [aarock1234/shopify-monitor#10]
Hi Team, I am having issues with the script
here is the entire command prompt whenever I try to start the script : 
[11:45:11:389] -------------------------
[11:45:11:394]    Shopify Monitor V2
[11:45:11:395]         By Rock
[11:45:11:395] -------------------------
[11:45:11:395] Found 18 sites.
[11:45:11:396] Found 20 proxies.
[11:45:11:396] -------------------------
[11:45:11:396] Initializing (18) sites.
[11:45:11:396] -------------------------
[11:45:11:673] Unhandled rejection RequestError: Error: tunneling socket could not be established, statusCode=503
    at new RequestError (/Users/adam/shopify-monitor/node_modules/request-promise-core/lib/errors.js:14:15)
    at Request.plumbing.callback (/Users/adam/shopify-monitor/node_modules/request-promise-core/lib/plumbing.js:87:29)
    at Request.RP$callback [as _callback] (/Users/adam/shopify-monitor/node_modules/request-promise-core/lib/plumbing.js:46:31)
    at self.callback (/Users/adam/shopify-monitor/node_modules/request/request.js:186:22)
    at Request.emit (events.js:223:5)
    at Request.onRequestError (/Users/adam/shopify-monitor/node_modules/request/request.js:878:8)
    at ClientRequest.emit (events.js:223:5)
    at ClientRequest.onConnect (/Users/adam/shopify-monitor/node_modules/tunnel-agent/index.js:168:23)
    at Object.onceWrapper (events.js:313:26)
    at ClientRequest.emit (events.js:223:5)
    at Socket.socketOnData (_http_client.js:490:11)
    at Socket.emit (events.js:223:5)
    at addChunk (_stream_readable.js:309:12)
    at readableAddChunk (_stream_readable.js:290:11)
    at Socket.Readable.push (_stream_readable.js:224:10)
    at TCP.onStreamRead (internal/stream_base_commons.js:181:23)

[11:45:13:720] Initialized - https://cncpts.com/
[11:45:14:288] Initialized - https://shop.ronniefieg.com/
[11:45:14:325] Initialized - https://www.kyliecosmetics.com/
[11:45:14:457] Initialized - https://stashedsf.com/
[11:45:14:793] Initialized - https://shop.exclucitylife.com/
[11:45:14:898] Initialized - https://pampamlondon.com/
[11:45:15:045] Initialized - https://shopnicekicks.com/
[11:45:16:466] Initialized - https://unknwn.com/
[11:45:17:241] Initialized - https://sneakerpolitics.com/
[11:45:17:733] Initialized - https://wishatl.com/
[11:45:18:346] Initialized - https://cityblueshop.com/
[11:45:18:653] Initialized - https://www.theclosetinc.com/
[11:45:18:933] Initialized - https://www.deadstock.ca/
[11:45:19:192] Initialized - https://packershoes.com/
[11:45:19:437] Initialized - https://suede-store.com/
[11:45:19:797] Initialized - https://www.xhibition.co/
[11:45:21:061] Initialized - https://shop.bdgastore.com/
^[[11:50:37:011] Unhandled rejection RequestError: Error: Client network socket disconnected before secure TLS connection was established
    at new RequestError (/Users/adam/shopify-monitor/node_modules/request-promise-core/lib/errors.js:14:15)
    at Request.plumbing.callback (/Users/adam/shopify-monitor/node_modules/request-promise-core/lib/plumbing.js:87:29)
    at Request.RP$callback [as _callback] (/Users/adam/shopify-monitor/node_modules/request-promise-core/lib/plumbing.js:46:31)
    at self.callback (/Users/adam/shopify-monitor/node_modules/request/request.js:186:22)
    at Request.emit (events.js:223:5)
    at Request.onRequestError (/Users/adam/shopify-monitor/node_modules/request/request.js:878:8)
    at ClientRequest.emit (events.js:223:5)
    at TLSSocket.socketErrorListener (_http_client.js:406:9)
    at TLSSocket.emit (events.js:223:5)
    at emitErrorNT (internal/streams/destroy.js:92:8)
    at emitErrorAndCloseNT (internal/streams/destroy.js:60:3)
    at processTicksAndRejections (internal/process/task_queues.js:81:21)

At first I thought it was my proxies being dead but even when I tried new ones I still get the same error. If someone is willing to help me it will be really appreciated. Thank you.

**Comment by ajfunelas** [comment]
add your own proxies in the proxies.txt

**Comment by adamh3105** [comment]
I already did but it still not working
