### ISSUE TITLE
Config.json file

### ISSUE THREAD

**Issue by saoheathcliff** [aarock1234/shopify-monitor#19]
So sorry, what is the config json file supposed to be? Currently I can only see 3 lines in it by following the instructions.

**Comment by saoheathcliff** [comment]
0 info it worked if it ends with ok
1 verbose cli [
1 verbose cli   'C:\\Program Files\\nodejs\\node.exe',
1 verbose cli   'C:\\Program Files\\nodejs\\node_modules\\npm\\bin\\npm-cli.js',
1 verbose cli   'start'
1 verbose cli ]
2 info using npm@6.14.13
3 info using node@v14.17.3
4 verbose run-script [ 'prestart', 'start', 'poststart' ]
5 info lifecycle shopify-monitor@1.0.0~prestart: shopify-monitor@1.0.0
6 info lifecycle shopify-monitor@1.0.0~start: shopify-monitor@1.0.0
7 verbose lifecycle shopify-monitor@1.0.0~start: unsafe-perm in lifecycle true
8 verbose lifecycle shopify-monitor@1.0.0~start: PATH: C:\Program Files\nodejs\node_modules\npm\node_modules\npm-lifecycle\node-gyp-bin;C:\Users\CW\shopify-monitor\node_modules\.bin;C:\Program Files (x86)\Razer\ChromaBroadcast\bin;C:\Program Files\Razer\ChromaBroadcast\bin;C:\Program Files (x86)\Razer Chroma SDK\bin;C:\Program Files\Razer Chroma SDK\bin;C:\Windows\system32;C:\Windows;C:\Windows\System32\Wbem;C:\Windows\System32\WindowsPowerShell\v1.0\;C:\Windows\System32\OpenSSH\;C:\Users\Administrator\AppData\Local\Microsoft\WindowsApps;C:\WINDOWS\system32;C:\WINDOWS;C:\WINDOWS\System32\Wbem;C:\WINDOWS\System32\WindowsPowerShell\v1.0\;C:\WINDOWS\System32\OpenSSH\;C:\Program Files\NVIDIA Corporation\NVIDIA NvDLISR;C:\Program Files (x86)\NVIDIA Corporation\PhysX\Common;C:\Users\CW\AppData\Local\Microsoft\WindowsApps;C:\WINDOWS\system32;C:\WINDOWS;C:\WINDOWS\System32\Wbem;C:\WINDOWS\System32\WindowsPowerShell\v1.0\;C:\WINDOWS\System32\OpenSSH\;C:\Program Files\nodejs\;C:\Program Files\Git\cmd;C:\Users\CW\AppData\Local\Microsoft\WindowsApps;C:\Users\CW\AppData\Roaming\npm
9 verbose lifecycle shopify-monitor@1.0.0~start: CWD: C:\Users\CW\shopify-monitor
10 silly lifecycle shopify-monitor@1.0.0~start: Args: [ '/d /s /c', 'node src/index.js' ]
11 silly lifecycle shopify-monitor@1.0.0~start: Returned: code: 1  signal: null
12 info lifecycle shopify-monitor@1.0.0~start: Failed to exec start script
13 verbose stack Error: shopify-monitor@1.0.0 start: `node src/index.js`
13 verbose stack Exit status 1
13 verbose stack     at EventEmitter.<anonymous> (C:\Program Files\nodejs\node_modules\npm\node_modules\npm-lifecycle\index.js:332:16)
13 verbose stack     at EventEmitter.emit (events.js:375:28)
13 verbose stack     at ChildProcess.<anonymous> (C:\Program Files\nodejs\node_modules\npm\node_modules\npm-lifecycle\lib\spawn.js:55:14)
13 verbose stack     at ChildProcess.emit (events.js:375:28)
13 verbose stack     at maybeClose (internal/child_process.js:1055:16)
13 verbose stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:288:5)
14 verbose pkgid shopify-monitor@1.0.0
15 verbose cwd C:\Users\CW\shopify-monitor
16 verbose Windows_NT 10.0.19042
17 verbose argv "C:\\Program Files\\nodejs\\node.exe" "C:\\Program Files\\nodejs\\node_modules\\npm\\bin\\npm-cli.js" "start"
18 verbose node v14.17.3
19 verbose npm  v6.14.13
20 error code ELIFECYCLE
21 error errno 1
22 error shopify-monitor@1.0.0 start: `node src/index.js`
22 error Exit status 1
23 error Failed at the shopify-monitor@1.0.0 start script.
23 error This is probably not a problem with npm. There is likely additional logging output above.
24 verbose exit [ 1, true ]

Full log of error obtained
