### ISSUE TITLE
Says error and I don't know what to do.

### ISSUE THREAD

**Issue by hamim23z** [aarock1234/shopify-monitor#2]
So I properly did all your steps and it shows me this. What do I do?

SyntaxError: /Users/hamim/shopify-monitor/config.json: Unexpected token t in JSON at position 971
    at parse (<anonymous>)
    at Object.Module._extensions..json (internal/modules/cjs/loader.js:1106:22)
    at Module.load (internal/modules/cjs/loader.js:928:32)
    at Function.Module._load (internal/modules/cjs/loader.js:769:14)
    at Module.require (internal/modules/cjs/loader.js:952:19)
    at require (internal/modules/cjs/helpers.js:88:18)
    at Object.<anonymous> (/Users/hamim/shopify-monitor/index.js:2:17)
    at Module._compile (internal/modules/cjs/loader.js:1063:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1092:10)
    at Module.load (internal/modules/cjs/loader.js:928:32)
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! shopify-monitor@1.4.1 start: `node index.js`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the shopify-monitor@1.4.1 start script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /Users/hamim/.npm/_logs/2020-11-22T22_23_49_157Z-debug.log
hamim@Hamims-Air shopify-monitor %

**Comment by aarock1234** [comment]
You did not follow the directions. Your config.json is malformed. Send a file upload here of it please.

**Comment by hamim23z** [comment]
> You did not follow the directions. Your config.json is malformed. Send a file upload here of it please.

<img width="1440" alt="Screen Shot 2020-11-23 at 12 23 50 PM" src="https://user-images.githubusercontent.com/74880822/99994246-c17d1600-2d86-11eb-9a0b-fae8d3e79b5d.png">

**Comment by hamim23z** [comment]
That's my config.json file

**Comment by aarock1234** [comment]
That is NOTHING like my file. I think you put an issue in the wrong repo. Closed.
