### ISSUE TITLE
Error when 'node index'

### ISSUE THREAD

**Issue by micbou80** [aarock1234/shopify-monitor#3]
internal/modules/cjs/loader.js:800
    throw err;
    ^

Error: Cannot find module 'request-promise'
Require stack:
- C:\Users\sneakernez\shopify-monitor\src\monitor.js
- C:\Users\sneakernez\shopify-monitor\task.js
- C:\Users\sneakernez\shopify-monitor\index.js
←[90m    at Function.Module._resolveFilename (internal/modules/cjs/
←[90m    at Function.Module._load (internal/modules/cjs/loader.js:6
←[90m    at Module.require (internal/modules/cjs/loader.js:852:19)←
←[90m    at require (internal/modules/cjs/helpers.js:74:18)←[39m
    at Object.<anonymous> (C:\Users\sneakernez\shopify-monitor\src\
←[90m    at Module._compile (internal/modules/cjs/loader.js:959:30)
←[90m    at Object.Module._extensions..js (internal/modules/cjs/loa
←[90m    at Module.load (internal/modules/cjs/loader.js:815:32)←[39
←[90m    at Function.Module._load (internal/modules/cjs/loader.js:7
←[90m    at Module.require (internal/modules/cjs/loader.js:852:19)←
  code: ←[32m'MODULE_NOT_FOUND'←[39m,
  requireStack: [
    ←[32m'C:\\Users\\sneakernez\\shopify-monitor\\src\\monitor.js'←
    ←[32m'C:\\Users\\sneakernez\\shopify-monitor\\task.js'←[39m,
    ←[32m'C:\\Users\\sneakernez\\shopify-monitor\\index.js'←[39m
  ]
}
PS C:\Users\sneakernez\shopify-monitor>

**Comment by Lauritz04** [comment]
getting the same error

**Comment by carlzoo** [comment]
This should have been in the README, but you need to type

```npm install```

then you run

```node index```
