### ISSUE TITLE
Error

### ISSUE THREAD

**Issue by Frm3** [aarock1234/shopify-monitor#4]
Unhandled rejection RequestError: Error: Invalid URI "https:///sitemap.xml"
    at new RequestError (C:\Users\domin\shopify-monitor\node_modules\request-promise-core\lib\errors.js:14:15)
    at Request.plumbing.callback (C:\Users\domin\shopify-monitor\node_modules\request-promise-core\lib\plumbing.js:87:29)
    at Request.RP$callback [as _callback] (C:\Users\domin\shopify-monitor\node_modules\request-promise-core\lib\plumbing.js:46:31)
    at self.callback (C:\Users\domin\shopify-monitor\node_modules\request\request.js:186:22)
    at Request.emit (events.js:210:5)
    at Request.init (C:\Users\domin\shopify-monitor\node_modules\request\request.js:274:17)
    at Request.RP$initInterceptor [as init] (C:\Users\domin\shopify-monitor\node_modules\request-promise-core\configure\request2.js:45:29)
    at new Request (C:\Users\domin\shopify-monitor\node_modules\request\request.js:128:8)
    at request (C:\Users\domin\shopify-monitor\node_modules\request\index.js:53:10)
    at initialize (C:\Users\domin\shopify-monitor\src\monitor.js:66:9)
    at new init (C:\Users\domin\shopify-monitor\src\monitor.js:48:7)
    at C:\Users\domin\shopify-monitor\index.js:30:14
    at Array.forEach (<anonymous>)
    at Object.<anonymous> (C:\Users\domin\shopify-monitor\index.js:29:7)
    at Module._compile (internal/modules/cjs/loader.js:959:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:995:10)
    at Module.load (internal/modules/cjs/loader.js:815:32)
    at Function.Module._load (internal/modules/cjs/loader.js:727:14)
    at Function.Module.runMain (internal/modules/cjs/loader.js:1047:10)
    at internal/main/run_main_module.js:17:11

**Comment by carlzoo** [comment]
Seems like an error caused by a newline in the txt file, I fixed it here: https://github.com/aarock1234/shopify-monitor/pull/6
