### ISSUE TITLE
Error when trying to install sites

### ISSUE THREAD

**Issue by Lauritz04** [aarock1234/shopify-monitor#5]
getting this when i type node index
Unhandled rejection RequestError: Error: Invalid URI "https:///sitemap.xml"
    at new RequestError (C:\Users\lauri\OneDrive\Desktop\shopify\shopify-monitor-master\node_modules\request-promise-core\lib\errors.js:14:15)
    at Request.plumbing.callback (C:\Users\lauri\OneDrive\Desktop\shopify\shopify-monitor-master\node_modules\request-promise-core\lib\plumbing.js:87:29)
    at Request.RP$callback [as _callback] (C:\Users\lauri\OneDrive\Desktop\shopify\shopify-monitor-master\node_modules\request-promise-core\lib\plumbing.js:46:31)
    at self.callback (C:\Users\lauri\OneDrive\Desktop\shopify\shopify-monitor-master\node_modules\request\request.js:186:22)
    at Request.emit (events.js:210:5)
    at Request.init (C:\Users\lauri\OneDrive\Desktop\shopify\shopify-monitor-master\node_modules\request\request.js:274:17)
    at Request.RP$initInterceptor [as init] (C:\Users\lauri\OneDrive\Desktop\shopify\shopify-monitor-master\node_modules\request-promise-core\configure\request2.js:45:29)
    at new Request (C:\Users\lauri\OneDrive\Desktop\shopify\shopify-monitor-master\node_modules\request\request.js:128:8)
    at request (C:\Users\lauri\OneDrive\Desktop\shopify\shopify-monitor-master\node_modules\request\index.js:53:10)
    at initialize (C:\Users\lauri\OneDrive\Desktop\shopify\shopify-monitor-master\src\monitor.js:66:9)
    at new init (C:\Users\lauri\OneDrive\Desktop\shopify\shopify-monitor-master\src\monitor.js:48:7)
    at C:\Users\lauri\OneDrive\Desktop\shopify\shopify-monitor-master\index.js:30:14
    at Array.forEach (<anonymous>)
    at Object.<anonymous> (C:\Users\lauri\OneDrive\Desktop\shopify\shopify-monitor-master\index.js:29:7)
    at Module._compile (internal/modules/cjs/loader.js:959:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:995:10)
    at Module.load (internal/modules/cjs/loader.js:815:32)
    at Function.Module._load (internal/modules/cjs/loader.js:727:14)
    at Function.Module.runMain (internal/modules/cjs/loader.js:1047:10)
    at internal/main/run_main_module.js:17:11

[22:49:44:677] Unhandled rejection RequestError: Error: tunneling socket could not be established, cause=connect ETIMEDOUT 196.53.195.45:8080
    at new RequestError (C:\Users\lauri\OneDrive\Desktop\shopify\shopify-monitor-master\node_modules\request-promise-core\lib\errors.js:14:15)
    at Request.plumbing.callback (C:\Users\lauri\OneDrive\Desktop\shopify\shopify-monitor-master\node_modules\request-promise-core\lib\plumbing.js:87:29)
    at Request.RP$callback [as _callback] (C:\Users\lauri\OneDrive\Desktop\shopify\shopify-monitor-master\node_modules\request-promise-core\lib\plumbing.js:46:31)
    at self.callback (C:\Users\lauri\OneDrive\Desktop\shopify\shopify-monitor-master\node_modules\request\request.js:186:22)
    at Request.emit (events.js:210:5)
    at Request.onRequestError (C:\Users\lauri\OneDrive\Desktop\shopify\shopify-monitor-master\node_modules\request\request.js:878:8)
    at ClientRequest.emit (events.js:210:5)
    at ClientRequest.onError (C:\Users\lauri\OneDrive\Desktop\shopify\shopify-monitor-master\node_modules\tunnel-agent\index.js:179:21)
    at Object.onceWrapper (events.js:300:26)
    at ClientRequest.emit (events.js:210:5)
    at Socket.socketErrorListener (_http_client.js:406:9)
    at Socket.emit (events.js:210:5)
    at emitErrorNT (internal/streams/destroy.js:92:8)
    at emitErrorAndCloseNT (internal/streams/destroy.js:60:3)
    at processTicksAndRejections (internal/process/task_queues.js:80:21)

**Comment by carlzoo** [comment]
Seems like an error caused by a newline in the txt file, I fixed it here: https://github.com/aarock1234/shopify-monitor/pull/6
