### ISSUE TITLE
 Unhandled rejection RequestError: Error: tunneling socket could not be established, statusCode=407

### ISSUE THREAD

**Issue by DirectiveCreator** [aarock1234/shopify-monitor#7]
Getting this a couple minutes after initializing.

Unhandled rejection RequestError: Error: tunneling socket could not be established, statusCode=407
    at new RequestError (C:\shopify-monitor\node_modules\request-promise-core\lib\errors.js:14:15)
    at Request.plumbing.callback (C:\shopify-monitor\node_modules\request-promise-core\lib\plumbing.js:87:29)
    at Request.RP$callback [as _callback] (C:\shopify-monitor\node_modules\request-promise-core\lib\plumbing.js:46:31)
    at self.callback (C:\shopify-monitor\node_modules\request\request.js:186:22)
    at Request.emit (events.js:210:5)
    at Request.onRequestError (C:\shopify-monitor\node_modules\request\request.js:878:8)
    at ClientRequest.emit (events.js:210:5)
    at ClientRequest.onConnect (C:\shopify-monitor\node_modules\tunnel-agent\index.js:168:23)
    at Object.onceWrapper (events.js:300:26)
    at ClientRequest.emit (events.js:210:5)
    at Socket.socketOnData (_http_client.js:490:11)
    at Socket.emit (events.js:210:5)
    at addChunk (_stream_readable.js:309:12)
    at readableAddChunk (_stream_readable.js:290:11)
    at Socket.Readable.push (_stream_readable.js:224:10)
    at TCP.onStreamRead (internal/stream_base_commons.js:182:23)

**Comment by Cherviakov** [comment]
Proxy auth failed, check credentials or try to use different proxy.

**Comment by Louiievuitton** [comment]
How do we add proxies ?

**Comment by jokzcooks** [comment]
Change them in proxies file in main folder
