### ISSUE TITLE
npm start: SyntaxError: Unexpected token

### ISSUE THREAD

**Issue by 0hn03** [aarock1234/shopify-monitor#8]
I've set everything up as you explained, yet when I run `npm start` I seem to get the following:

```
> shopify-monitor@1.0.0 start /root/shopify-bot
> node src/index.js

/root/shopify-bot/src/class/monitor.js:54
    randomProxy = () => {
                ^

SyntaxError: Unexpected token =
    at Module._compile (internal/modules/cjs/loader.js:723:23)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:789:10)
    at Module.load (internal/modules/cjs/loader.js:653:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:593:12)
    at Function.Module._load (internal/modules/cjs/loader.js:585:3)
    at Module.require (internal/modules/cjs/loader.js:692:17)
    at require (internal/modules/cjs/helpers.js:25:18)
    at Object.<anonymous> (/root/shopify-bot/src/index.js:1:17)
    at Module._compile (internal/modules/cjs/loader.js:778:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:789:10)
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! shopify-monitor@1.0.0 start: `node src/index.js`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the shopify-monitor@1.0.0 start script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /root/.npm/_logs/2021-01-18T02_26_57_158Z-debug.log
```

Full log:
```
0 info it worked if it ends with ok
1 verbose cli [ '/usr/bin/node', '/usr/bin/npm', 'start' ]
2 info using npm@6.14.4
3 info using node@v10.19.0
4 verbose run-script [ 'prestart', 'start', 'poststart' ]
5 info lifecycle shopify-monitor@1.0.0~prestart: shopify-monitor@1.0.0
6 info lifecycle shopify-monitor@1.0.0~start: shopify-monitor@1.0.0
7 verbose lifecycle shopify-monitor@1.0.0~start: unsafe-perm in lifecycle true
8 verbose lifecycle shopify-monitor@1.0.0~start: PATH: /usr/share/npm/node_modules/npm-lifecycle/node-gyp-bin:/root/shopify-bot/node_modules/.bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/usr/games:/usr/local/games:/snap/bin
9 verbose lifecycle shopify-monitor@1.0.0~start: CWD: /root/shopify-bot
10 silly lifecycle shopify-monitor@1.0.0~start: Args: [ '-c', 'node src/index.js' ]
11 silly lifecycle shopify-monitor@1.0.0~start: Returned: code: 1  signal: null
12 info lifecycle shopify-monitor@1.0.0~start: Failed to exec start script
13 verbose stack Error: shopify-monitor@1.0.0 start: `node src/index.js`
13 verbose stack Exit status 1
13 verbose stack     at EventEmitter.<anonymous> (/usr/share/npm/node_modules/npm-lifecycle/index.js:332:16)
13 verbose stack     at EventEmitter.emit (events.js:198:13)
13 verbose stack     at ChildProcess.<anonymous> (/usr/share/npm/node_modules/npm-lifecycle/lib/spawn.js:55:14)
13 verbose stack     at ChildProcess.emit (events.js:198:13)
13 verbose stack     at maybeClose (internal/child_process.js:982:16)
13 verbose stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:259:5)
14 verbose pkgid shopify-monitor@1.0.0
15 verbose cwd /root/shopify-bot
16 verbose Linux 5.4.0-62-generic
17 verbose argv "/usr/bin/node" "/usr/bin/npm" "start"
18 verbose node v10.19.0
19 verbose npm  v6.14.4
20 error code ELIFECYCLE
21 error errno 1
22 error shopify-monitor@1.0.0 start: `node src/index.js`
22 error Exit status 1
23 error Failed at the shopify-monitor@1.0.0 start script.
23 error This is probably not a problem with npm. There is likely additional logging output above.
24 verbose exit [ 1, true ]
```

Any ideas?

**Comment by aarock1234** [comment]
This is odd, mind sending me your node version? Get that by typing `node -v` in the command prompt.

**Comment by 0hn03** [comment]
v10.19.0

**Comment by aarock1234** [comment]
Your node version is outdated, but I am not sure why that would cause such an issue. This is an issue with running files in general, which is weird. This is non-specific to the monitor. So what I would do is install the newest version of node. I am on `v12.16.2` which is what I wrote it on aswell. Try that and report back if possible.

**Comment by 0hn03** [comment]
That fixed it! Thanks. 

This is probably my own fault but any reason why I might be getting
```
[[02:50:46.204] [LOG]    Monitor Started for http://sneaky-petes-sneakers.myshopify.com/
[02:50:46.462] [ERROR]  INIT ERR @ http://www.soleseriouss.com: Error: Exceeded maxRedirects. Probably stuck in a redirect loop http://www.soleseriouss.com/products.json?limit=6555
```

Is this because I havent set up SSL?

**Comment by 0hn03** [comment]
That fixed it, thanks!
```
[02:51:08.215] [LOG]    Monitor Started for https://websitename.com/
[02:51:08.510] [ERROR]  INIT ERR @ https://www.websitename.com: Error [ERR_TLS_CERT_ALTNAME_INVALID]: Hostname/IP does not match certificate's altnames: Host: www.websitename.com. is not in the cert's altnames: DNS:myshopify.com, DNS:*.myshopify.com
```

Any reason why I might be getting this? Maybe because I didnt set up SSL?

Just using this website to test, but seems to be happening to all.

**Comment by aarock1234** [comment]
This is also odd... Are you running on a secure network? Try monitoring `https://www.kith.com`

**Comment by 0hn03** [comment]
Strange. Works for Kith. Changed it back and it's all working again! Thanks so much for your help

**Comment by 0hn03** [comment]
Oh I found out what was happening. That website seems to have that error if it's inputted at `www.websitename.com` but not when it's `websitename.com`
